CREATE TABLE IF NOT EXISTS cls(
    number INT(11) AUTO_INCREMENT NOT NULL PRIMARY KEY COMMENT '班级编号,主键',
    name VARCHAR(20) NOT NULL COMMENT '班级名称',
    grade VARCHAR(20) NOT NULL COMMENT '年级'
)ENGINE=InnoDB CHARSET=UTF8 COMMENT='班级表';

CREATE TABLE IF NOT EXISTS student(
    number BIGINT(20) AUTO_INCREMENT NOT NULL COMMENT '学号,主键',
    name VARCHAR(20) NOT NULL COMMENT '姓名',
    sex VARCHAR(2) DEFAULT '男' COMMENT '性别:男,女,其他',
    age TINYINT(3) DEFAULT 0 COMMENT '年龄',
    cls_number INT(11) NOT NULL COMMENT '班级编号,外键',
    
)ENGINE=InnoDB CHARSET=UTF8 COMMENT='学生表';